### ISSUE TITLE
Допом: перепиши в функциональном стиле.

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#1]
![image](https://user-images.githubusercontent.com/101792032/176900964-bb40f05e-4297-42af-84ea-ecdc90f7f73a.png)

Конструкция `age >= 14 && age <= 90` это типичный процедурный прикольчик.

Это можно переписать функционально и переиспользовать.

```
const isValidAge = (age) => isInRange(14)(90)

const isInRange = ???

let age = 42;

If (isValidAge(age)) {
  alert("Functional Programming")  
}
```

**Comment by VKNagibin** [comment]
Done!

**Comment by mordvinian** [comment]
![image](https://user-images.githubusercontent.com/101792032/177976298-676ee9ed-c8c5-4850-b9a9-0f9a977d55ad.png)
Тебе не подсвечивает что ли?)

**Comment by mordvinian** [comment]
![image](https://user-images.githubusercontent.com/101792032/177976353-22fa15cc-7e81-46f0-841c-2f7f57960922.png)

**Comment by VKNagibin** [comment]
dev f21ddf2
