### ISSUE TITLE
Допом: перепиши на ФП

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#11]
![image](https://user-images.githubusercontent.com/101792032/177980578-747f4a43-cb5e-47ba-b36a-c681df521c08.png)

Попробуй сделать это на фп

**Comment by VKNagibin** [comment]
Вероятно, есть решение намного проще, но это уже другая история...
dev 2b4864a

**Comment by VKNagibin** [comment]
dev 07c1839

**Comment by mordvinian** [comment]
Молодец!
