### ISSUE TITLE
На заметку: клонирование через JSON 

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#13]
![image](https://user-images.githubusercontent.com/101792032/177982868-f891f935-1b47-44a5-b50e-0e100662241c.png)

Объект из JSON не равен изначальному объекту. 

Объекты в JS передаются по ссылке, как ты помнишь, но в случае с JSON создается новый объект (независимый)

**Comment by VKNagibin** [comment]
Супер классная заметка, но увы, я в курсе. Единственный (на сколько я знаю) способ избавиться от ссылки на объект, если объект хранит в себе вложенные объекты

**Comment by mordvinian** [comment]
Вообще не единственный, и пожалуй самый хреновый способ копировать объекты)

На самом деле есть алгоритмы клонирования, они не особо сложные, но там рекурсия чтобы было можно работать с вложенными объектами

**Comment by VKNagibin** [comment]
А что не так с этим способом?

**Comment by mordvinian** [comment]
Он медленный, потому что работает со строкой json.
связка stringify + parse по сути сначала создает строку из объекта, потом делает объект из строки. Это дороже, чем просто перебрать все ключи объекта рекурсивно
