### ISSUE TITLE
Очень хорошо, но не SOLIDно

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#14]
![image](https://user-images.githubusercontent.com/101792032/178430546-2747a06c-9baf-4244-8419-f36ec57abafb.png)

Решение чистое, но не расширяемое.

Здесь можно потренироваться делать по солиду, т.к. на лицо процедурный подход.

Что нужно сделать:
1. Правила, по которым мы валидируем (регулярки) находятся прямо в теле функции. Мы не можем их изменять или добавлять, не залезая в код функции

2. При добавлении нового правила, нужно также добавить его в список проверок.

Подсказываю: создай массив запрещенных паттернов, и проверь что строка их содержит.

**Comment by VKNagibin** [comment]
dev 473a58e  если я правильно понял

**Comment by mordvinian** [comment]
Молодец, но это еще не функциональный стиль)
Хотя классно получилось, понял правильно

Вариант маэстро
![image](https://user-images.githubusercontent.com/101792032/178700357-a8094374-bf31-439f-a6f6-5057345981b1.png)

**Comment by mordvinian** [comment]
Лучше выносить отдельно такие вещи как badPatterns, чтобы не искать их внутри тела функций. Это буковка S из SOLID

**Comment by mordvinian** [comment]
В моем варианте есть возможность грузить разные словари => меньше нарушений DRY
