### ISSUE TITLE
камелизация страшная получилась

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#15]
![image](https://user-images.githubusercontent.com/101792032/178435496-a0d836ae-0bca-4774-b3bc-0426a5e58ea6.png)

ФП вариант от маэстро для общего ознакомления, возьми на заметку

По косякам:

1. зачем нестрогое сравнение в самом верху? Что оно делает вообще?
2. `array_` ?

**Comment by VKNagibin** [comment]
Пиздец, реально маэстро, вообще не читаемо) Нестрогое сравнение вверху было в задании, просто скопировал.
За второе поясню в issue по теме
