### ISSUE TITLE
Страшно

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#16]
![image](https://user-images.githubusercontent.com/101792032/178436302-60366820-d358-4df3-b57e-38cd7a0608ef.png)

1. a и b плохие имена для аргументов. Как для пользователя, так и того, кто туда полезет. Если ты используешь однобуквенные переменные - у тебя должна быть причина так делать. Чистый код.

2. Можно не создавать переменную и в целом написать короче, ФП пример ниже. В данном случае ФП пример не для общего развития, а тут реально так будет короче и проще

**Comment by VKNagibin** [comment]
dev a215968
