### ISSUE TITLE
Сломается на const 

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#17]
![image](https://user-images.githubusercontent.com/101792032/178437508-9ed62590-338e-470d-a224-7812ea9fe6c4.png)

Если поменять на const, то попытка сделать arr = придет к ошибке.

**Comment by VKNagibin** [comment]
https://prnt.sc/PRNcRgeRewcl 
Ну как бы задание в том и заключается, что мы изменяем исходный массив, фильтруем "на месте". 
Добавил ниже решение внутри чистой функции
dev 92c602f

**Comment by mordvinian** [comment]
Можно отфильтровать массив на месте, при этом чтобы не ломалось на конст, подумай.

просто нужно решить задачу без использования `arr = ...`

**Comment by VKNagibin** [comment]
Я же кинул коммит, там чистая функция, она arr не меняет
https://github.com/VKNagibin/WorkSolutions-JS-tasks/commit/92c602fbb9764d4f2cf40b451e4fe17cd86430b8

**Comment by mordvinian** [comment]
Сейчас объясню.
У тебя есть переменная arr. После вызова `filterRangeInPlace` arr должна измениться. Это значит "на месте", то есть на том же массиве, который был.

Но использовать `arr = ...` нельзя, т.к. при использовании const функция сломается и выдаст ошибку.

Нужно изменить переменную arr, но так, чтобы работало и с const тоже.

**Comment by VKNagibin** [comment]
[c82a5f1](https://github.com/VKNagibin/WorkSolutions-JS-tasks/commit/c82a5f17834f16dbfa1c1d3cacbce87e8514da1c)
