### ISSUE TITLE
Можно решить в 1 строчку

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#18]
![image](https://user-images.githubusercontent.com/101792032/178438011-8ea1dcd4-1853-4f9c-b951-e0ed22f1c90a.png)

На самом деле тут даже if не нужен.

Не стоит использовать == т.к. есть ===

**Comment by VKNagibin** [comment]
dev e9f0b10

**Comment by mordvinian** [comment]
Когда я говорил, что if не нужен, я имел ввиду что тут в принципе условия не нужны
```
const sortFunc = (a, b) => b-a
```

**Comment by mordvinian** [comment]
Если a > b то b - a <= -1

**Comment by VKNagibin** [comment]
dev d6c5fdb
