### ISSUE TITLE
Можно решить в 1 строчку

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#19]
![image](https://user-images.githubusercontent.com/101792032/178438382-78e417f6-6bb5-4ada-aa31-db9dadef3806.png)

Можно решить в одну строчку без потерь в читаемости
использовать array_ не стоит, ничего не сломается если ты используешь arr или array

Array трогать не надо)

**Comment by VKNagibin** [comment]
dev 7634533
