### ISSUE TITLE
Эта хеьрня не работает.

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#2]
https://github.com/VKNagibin/WorkSolutions-JS-tasks/blob/f783b564a1cacfa9e717fd250ab7730e9673a076/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%20JavaScript/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8.js#L25-L31

Пруф:
![image](https://user-images.githubusercontent.com/101792032/176902587-106dec15-2d81-4873-8f94-846ecb0a11db.png)

**Comment by VKNagibin** [comment]
Фиксики всё починили
