### ISSUE TITLE
Где ты взял привычку так подписывать переменные?

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#21]
![image](https://user-images.githubusercontent.com/101792032/178495368-643f60b6-36ae-4e01-8588-5807d8642431.png)

Я не понимаю прикола с prompt_ и другими значениями. Не могу прям жоска утвердить, но по-моему это все же коричневая тема.

Если обозвать как promptedMessage будет чуть лучше читаться, так что лучше поменять.

Где ты этому научился?)

**Comment by mordvinian** [comment]
Я серьезно, ты где-то это подсмотрел, или сам придумал?

**Comment by mordvinian** [comment]
Все остальное можно принять, но не это
![image](https://user-images.githubusercontent.com/101792032/178497005-bd299f97-7988-4564-884c-6e651cb1a708.png)
![image](https://user-images.githubusercontent.com/101792032/178497051-446f257e-60a2-4c08-8867-6a60c5a1e8ae.png)

**Comment by VKNagibin** [comment]
dev 7f6f110
Дружбан у меня есть фронтендер. У него и перенял switch_. Может коричнево, я хз

**Comment by mordvinian** [comment]
Лучше так не надо делать

**Comment by VKNagibin** [comment]
Бросил эту пагубную привычку
