### ISSUE TITLE
???

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#22]
![image](https://user-images.githubusercontent.com/101792032/178497671-156b5471-8286-4ee4-a4ae-43570f57f6fa.png)

Забыл?

**Comment by VKNagibin** [comment]
dev 9c53b9a
Походу забыл

**Comment by mordvinian** [comment]
Плохо, оставил комменты 

Можно проще
```
const getTopSalaryEmployeeName = (salaries = {}) => Object.entries(salaries)
  .reduce(([accName, accSalary], [name, salary]) => {
      return salary > accSalary
        ? [name,salary]
        : [accName, accSalary]
    }, [null, 0]
  )[0]
  ```

**Comment by mordvinian** [comment]
https://github.com/VKNagibin/WorkSolutions-JS-tasks/commit/9c53b9a8b633dd24150e8fe8ddb1326f74de98fb

**Comment by VKNagibin** [comment]
Как тебе такое, Илон Маск?
4daab4c
