### ISSUE TITLE
Тут можно проще

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#23]
![image](https://user-images.githubusercontent.com/101792032/178498131-b7613e3c-6318-4ddf-8487-f49d29f1230a.png)

Попробуй убрать свитч

**Comment by mordvinian** [comment]
Огромный бойлерплейт, который на самом деле можно заменить очень просто + добавить SOLIDности коду

**Comment by mordvinian** [comment]
Старайся фокусироваться в те моменты, когда (по возрастанию):
1. ты пишешь if
2. ты пишешь if else
3. ты пишешь switch

Думай как переписать, если начинаешь создавать вложенные структуры, while + if else, switch + if else и др.

Можно не думать если ты используешь if (condition) return, это называется early return pattern 
https://habr.com/ru/post/348074/

**Comment by mordvinian** [comment]
Еще триггеры, которые тоже следует подмечать:

1. В блоке условия больше одного оператора (a && b) еще пойдет, (a || b && c) уже заставляет включать думалку.
(a1 && a2 && a3 && ...an) легко заменяется на arr.every

2. после того как ты пишешь if (condition) {...} у тебя ничего не происходит, значит это можно сконвертировать в earlyReturn pattern

**Comment by VKNagibin** [comment]
dev 2b92e71

**Comment by mordvinian** [comment]
Все равно шляпа
`let daysArray = ['ВС','ПН', 'ВТ','СР','ЧТ','ПТ','СБ'];
return daysArray[date.getDay()];`

**Comment by VKNagibin** [comment]
52699ea

**Comment by VKNagibin** [comment]
ну это конечно спорный вопрос. Я здесь воссоздал массив дней недели по порядку, это чуть-чуть сложнее

**Comment by mordvinian** [comment]
А не нужно было по порядку. Если бы тут был TS, то функция принимала бы объект Date, и ничего кроме. Так что такая реализация проще.
