### ISSUE TITLE
А где третий вариант?

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#24]
![image](https://user-images.githubusercontent.com/101792032/178500841-f7ff57da-7835-483d-8fb8-48234cf0944f.png)

Должен быть вариант с использованием формулы арифметической прогрессии.

Ответы на вопросы из задания (про скорость и рекурсию) жду здесь письменно, или устно лично. Отмазаться не вариант)

**Comment by VKNagibin** [comment]
dev e9acf08

https://prnt.sc/CiexTMcvP-e-
Решение с использованием формулы арифметической прогрессии является самым быстрым, т.к. один раз происходит вычисление значения и возвращается результат. Рекурсия оказалась самым медленным способом, т.к. необходимы дополнительные временные затраты на вложенные вызовы. Посчитать sumTo(100000) нельзя, т.к. переполнится стек.
Результаты тестов на скриншоте
