### ISSUE TITLE
)

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#25]
![image](https://user-images.githubusercontent.com/101792032/178502117-b84e9df9-0115-471a-9b86-d14fddc6b5c2.png)
![image](https://user-images.githubusercontent.com/101792032/178502182-3f194a1e-f4dc-4bd2-af24-4df9be9da428.png)
![image](https://user-images.githubusercontent.com/101792032/178502236-1472677b-f481-4ad7-b223-348700e83baf.png)
![image](https://user-images.githubusercontent.com/101792032/178502346-51b171b5-8d16-44c4-beb1-a21056b32037.png)

**Comment by mordvinian** [comment]
Можно изменять только указанную строку

```
let bindLoginOk = user.loginOk.bind(user);
let bindLoginFail = user.loginFail.bind(user);
```
Не соответствует критериям задачи

**Comment by mordvinian** [comment]
```
askPassword(user.loginOk.bind(user),user.loginFail.bind(user));
```

т.к. с байндами ты уже разобрался, давай этот вариант уберем потому что нечитается нихера
Давай еще один

**Comment by VKNagibin** [comment]
dev 469bbda
Не понял где ещё один, этот исправил

**Comment by mordvinian** [comment]
Байнд не нужен
function askPassword(ok, fail) {
    let password = prompt("Password?", '');
    if (password == "rockstar") ok();
    else fail();
}

let user = {
    name: 'Вася',

    loginOk() {
        alert(`${this.name} logged in`);
    },

    loginFail() {
        alert(`${this.name} failed to log in`);
    },

};

askPassword(() => user.loginOk(), () => user.loginFail());

**Comment by VKNagibin** [comment]
7ade4fe
