### ISSUE TITLE
Дополнительные материалы

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#26]
https://learn.javascript.ru/generators - маст хэв если хочешь понять что такое редакс сага

https://learn.javascript.ru/with - просто если интересно, какое говно бывает встречается в js

https://learn.javascript.ru/proxy - маст хэв для vue3

https://learn.javascript.ru/property-accessors 
и еще
https://learn.javascript.ru/property-descriptors

Это мастхэв для vue2

**Comment by mordvinian** [comment]
Если хочешь упороться по-крупному:

https://learn.javascript.ru/currying-partials - sum(4)(2)(5)()
https://learn.javascript.ru/bitwise-operators - скорее всего никогда не пригодится, но если вдруг пригодится - надо знать.

https://learn.javascript.ru/eval

**Comment by VKNagibin** [comment]
Спасибо, ссылочки сохранил, закрываю
