### ISSUE TITLE
Чаще смотри в сторону лямбда-функций

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#27]
![image](https://user-images.githubusercontent.com/101792032/178504706-34934259-af61-4956-a468-fcf1f4c77574.png)
Все классно, круто, но лямбда короче, и тут это не вредит читаемости.

Лямбда чуть сложнее стандартных функций, но освоив их ты обретешь истинную мощь

**Comment by mordvinian** [comment]
Основной аргумент - у тебя так не будет расти вложенность, поэтому читать проще

**Comment by VKNagibin** [comment]
dev 10954d6
Отрефакторил
