### ISSUE TITLE
Процедурное программирование

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#28]
![image](https://user-images.githubusercontent.com/101792032/178505381-9fcfa5d8-445b-4fe5-8380-f69c942b6404.png)

if точно нужно упрощать.

Можешь попробовать переписать чуть более функционально.

**Comment by VKNagibin** [comment]
dev 721d00b

**Comment by mordvinian** [comment]
Хорошо, молодец
