### ISSUE TITLE
Для пробрасывания аргументов используй ...args 

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#29]
![image](https://user-images.githubusercontent.com/101792032/178505948-179b1fab-529d-4d02-b842-7598e7bfc4d9.png)

**Comment by mordvinian** [comment]
Если тебе нужно просто прокинуть входные данные дальше, то лучше всего это делать через ...args

В нормальных языках насколько знаю так и делается

**Comment by VKNagibin** [comment]
Ага, усвоил. 
dev 8d75824
