### ISSUE TITLE
Ты молодец

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#3]
https://github.com/VKNagibin/WorkSolutions-JS-tasks/blob/f783b564a1cacfa9e717fd250ab7730e9673a076/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%20JavaScript/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8.js#L43-L51

Рекурсия это хорошо, молодец. Иногда сложные вещи через рекурсию решаются намного проще.

Тем не менее, любую рекурсию можно перевести в цикл, и наоборот.

А еще она не работает с такими аргументами) Не забывай обрабатывать крайние случаи)
![image](https://user-images.githubusercontent.com/101792032/176902983-4476282b-6aeb-4403-94e9-017e68e7bb1a.png)

**Comment by VKNagibin** [comment]
Добавил валидацию

**Comment by mordvinian** [comment]
![image](https://user-images.githubusercontent.com/101792032/177975793-f7027dd7-6dbe-417c-b63f-74b781272825.png)

return без ничего фактически возвращает undefined. Тут уместнее будет возвращать NaN для солидарности с философией JS

**Comment by mordvinian** [comment]
Если ты будешь делать какую-то фигню с числами JS всегда тебе вернет NaN в самом крайнем случае. Например, при делении на ноль.

Так что логичнее это продолжать в функциях, которые пишешь

**Comment by VKNagibin** [comment]
Усвоил, исправил dev d0ae672
