### ISSUE TITLE
На заметку: имя конструктора можно получить

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#30]
![image](https://user-images.githubusercontent.com/101792032/178508692-7274d22c-0d3f-4c63-a27b-5f37f8015dac.png)

Ты можешь получить имя конструктора через this.constructor.name

Т.к. конструктор - функция, то ты в принципе можешь получить имя функции.

![image](https://user-images.githubusercontent.com/101792032/178509178-beab1751-47f8-440f-96b2-1ebb1aaab63d.png)

`(function(){}).name`
Тут создается функция, которая ничего не делает. Т.к. функция анонимная (ты это уже видел в NFE), у нее нет name

**Comment by VKNagibin** [comment]
Понял, спасибо за инфу
