### ISSUE TITLE
Это так не работает, хунта

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#32]
![image](https://user-images.githubusercontent.com/101792032/178513090-928341d2-d7e2-4f0e-8fbd-c375d2ca946a.png)

**Comment by mordvinian** [comment]
НЕ ИСПОЛЬЗУЙ == БУЛДЖАДЬ

**Comment by mordvinian** [comment]
У тебя здесь ошибка, всегда будет ошибка

**Comment by VKNagibin** [comment]
dev a9c68ad
