### ISSUE TITLE
Хорошая идея, но тут неуместна

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#4]
![image](https://user-images.githubusercontent.com/101792032/176903571-8bc5b672-2b7a-4747-af08-9601807612b7.png)

Если ты написал number_ чтобы дать отличие от класса Number, то зря. 
И обычно лодаш ставят перед словом, как префикс.

Это уместно когда байндишь контекст

`const _this = this`

**Comment by mordvinian** [comment]
Либо объясни науйх ты это сделал, потому что я чет не понял

**Comment by VKNagibin** [comment]
Ты правильно понял: чтобы дать отличие от класса Number. Больше не буду)
