### ISSUE TITLE
Да, но нет

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#5]
https://github.com/VKNagibin/WorkSolutions-JS-tasks/blob/f783b564a1cacfa9e717fd250ab7730e9673a076/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B%20JavaScript/%D0%A6%D0%B8%D0%BA%D0%BB%D1%8B%20while%20%D0%B8%20for.js#L55-L71

Не обработает корректно числа меньше 2

Зачем отдаешь сразу строку? Может лучше отдать массив чисел, а потом его вывести в консоль?

**Comment by VKNagibin** [comment]
Код больше не коричневый)

**Comment by mordvinian** [comment]
![image](https://user-images.githubusercontent.com/101792032/177976634-d1f9d3f4-bc83-4c2d-a156-4045ae49eff6.png)

Подтирайся начисто)

**Comment by mordvinian** [comment]
![image](https://user-images.githubusercontent.com/101792032/177977158-f3fb1699-4cd2-4903-855c-8a4d992f525a.png)

**Comment by mordvinian** [comment]
Хипстерский трюк называется "оператор защиты", лол. Но лучше его не используй, обычно так хуже читается.

Склеивать массив в строку не стоит потому что:

- Со строкой сложнее работать, чем с массивом
- Это нарушает SRP, у функции есть больше одного вектора изменений. Мы можем захотеть поменять логику, или форматирование.

На самом деле функция еще и валидирует аргументы, так что SRP тут все равно нарушен. Но в этом примере это не критично

**Comment by VKNagibin** [comment]
Готово dev d5f6f13
