### ISSUE TITLE
Либо declaration, либо expression, а тут какая-то дичь

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#6]
![image](https://user-images.githubusercontent.com/101792032/177977944-84a1807a-d5a6-483c-9872-16f8522d8a63.png)

Выглядит плохо, потому что это expression который пытается косить под declaration

![image](https://user-images.githubusercontent.com/101792032/177977922-2c2ab906-ddbc-42e5-aba8-bb9eb58911ea.png)

**Comment by mordvinian** [comment]
В таких коротких кейсах лучше писать стрелки, 
В длинных уместно 

```
    this.sum = () => {
        // do some stuff
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // do more stuff
        return +this.num1 + +this.num2;
    }
    ```

**Comment by mordvinian** [comment]
```
 function sum() {
        // do some stuff
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // do more stuff
        return +this.num1 + +this.num2;
    }
```

**Comment by mordvinian** [comment]
Хотя второй кейс все равно проще

**Comment by VKNagibin** [comment]
Угу, зарубил себе на носу, как говорится, спасибо. 
dev 8bf48d7
