### ISSUE TITLE
Обработка крайних случаев

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#7]
![image](https://user-images.githubusercontent.com/101792032/177978492-fa18c900-ea7b-4a0d-a47b-a9c9f937920c.png)

А если будет NaN? У тебя в аккумуляторе навсегда останется инвалидное значение, и его никак не сбросить

**Comment by VKNagibin** [comment]
Исправлено dev 5d2f8d2

**Comment by mordvinian** [comment]
Хорошо!
