### ISSUE TITLE
А почему тут не возвращается this?

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#8]
![image](https://user-images.githubusercontent.com/101792032/177978805-2994ba0a-a74a-4eff-a977-672b6755a08e.png)

Если ты его можешь вернуть, то почему не возвращаешь? 
Вообще, если смотреть на это как на библиотечный код, то будет полезно вернуть либо this.step, либо this.

Лучше всего будет вернуть this.

**Comment by VKNagibin** [comment]
dev 268c5aa
