### ISSUE TITLE
Можно лучше

### ISSUE THREAD

**Issue by mordvinian** [VKNagibin/WorkSolutions-JS-tasks#9]
![image](https://user-images.githubusercontent.com/101792032/177979934-c688a51b-5870-4b74-aafa-55c333c63baf.png)

Первый вариант будет работать быстрее, если добавить брейк

Второй тупо короче и понятнее

**Comment by mordvinian** [comment]
Ток наоборот, true false перепутал

**Comment by VKNagibin** [comment]
Отрефакторил dev 59e3663
